import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../Services/pos_service.dart';

class ReportingScreen extends StatefulWidget {
  const ReportingScreen({super.key});

  @override
  State<ReportingScreen> createState() => _ReportingScreenState();
}

class _ReportingScreenState extends State<ReportingScreen> {
  final String _selectedDate = '2025-10-01';

  @override
  void initState() {
    super.initState();
    final posService = Provider.of<PosService>(context, listen: false);
    posService.fetchSalesReport();
    posService.fetchDailySalesReport(_selectedDate);
    posService.fetchTaxReport(_selectedDate);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Sales and Tax Reports'),
        backgroundColor: Colors.deepOrange,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Consumer<PosService>(
          builder: (context, posService, child) {
            return Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Overall Sales Report
                Card(
                  elevation: 4,
                  child: Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          'Overall Sales Summary',
                          style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                        ),
                        const SizedBox(height: 8),
                        if (posService.salesReport == null)
                          const Text('Loading overall sales...')
                        else ...[
                          Text('Total Invoices: ${posService.salesReport!['total_invoices']}'),
                          Text('Total Sales: K${posService.salesReport!['total_sales'].toStringAsFixed(2)}'),
                          Text('Total Tax: K${posService.salesReport!['total_tax'].toStringAsFixed(2)}'),
                          Text('Generated By: ${posService.salesReport!['generated_by']}'),
                        ],
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 16),
                // Daily Sales Report
                Card(
                  elevation: 4,
                  child: Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Daily Sales Report ($_selectedDate)',
                          style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                        ),
                        const SizedBox(height: 8),
                        if (posService.dailySalesReport == null)
                          const Text('Loading daily sales...')
                        else ...[
                          Text('Total Sales: K${posService.dailySalesReport!['total_sales'].toStringAsFixed(2)}'),
                          const SizedBox(height: 8),
                          ...posService.dailySalesReport!['orders'].map<Widget>((order) => Text(
                              'Order ID: ${order['id']}, Product: ${order['product_id']}, Qty: ${order['quantity']}, Total: K${order['total_price'].toStringAsFixed(2)}'
                          )).toList(),
                        ],
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 16),
                // Tax Report
                Card(
                  elevation: 4,
                  child: Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Tax Report ($_selectedDate)',
                          style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                        ),
                        const SizedBox(height: 8),
                        if (posService.taxReport == null)
                          const Text('Loading tax report...')
                        else ...[
                          Text('Total Tax: K${posService.taxReport!['total_tax'].toStringAsFixed(2)}'),
                          const SizedBox(height: 8),
                          ...posService.taxReport!['invoices'].map<Widget>((invoice) => Text(
                              'Invoice ID: ${invoice['id']}, CIS No: ${invoice['cis_invc_no']}, Total: K${invoice['total_amount'].toStringAsFixed(2)}, Tax: K${invoice['tax_amount'].toStringAsFixed(2)}'
                          )).toList(),
                        ],
                      ],
                    ),
                  ),
                ),
              ],
            );
          },
        ),
      ),
    );
  }
}