openapi: 3.0.0
info:
  title: Student B Invoice Submission API
  version: 1.0.0
  description: >
    FastAPI backend for Student B deliverable.  
    Provides endpoints to submit invoices to a simulated Tax Authority system
    with success and failure responses.
servers:
  - url: http://127.0.0.1:8000/api
    description: Local development server
paths:
  /invoices/submit:
    post:
      summary: Submit invoice (Success case)
      description: Returns a success response from the Tax Authority.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invoice'
      responses:
        '200':
          description: Invoice accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
  /invoices/fail:
    post:
      summary: Submit invoice (Failure case)
      description: Returns a simulated failure from the Tax Authority.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invoice'
      responses:
        '400':
          description: Invoice rejected
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailResponse'
components:
  schemas:
    Invoice:
      type: object
      properties:
        tpin:
          type: string
          example: "123456789"
        bhfId:
          type: string
          example: "001"
        deviceSerialNo:
          type: string
          example: "POS-01"
        invcNo:
          type: string
          example: "INV_20251003_001"
        salesDt:
          type: string
          format: date-time
          example: "2025-10-03T14:30:00Z"
        invoiceType:
          type: string
          example: "N"
        transactionType:
          type: string
          example: "SALE"
        paymentType:
          type: string
          example: "CASH"
        customerTpin:
          type: string
          example: "987654321"
        customerNm:
          type: string
          example: "John Banda"
        totalItemCnt:
          type: integer
          example: 2
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
        totTaxblAmt:
          type: number
          example: 100.0
        totTaxAmt:
          type: number
          example: 10.0
        totAmt:
          type: number
          example: 110.0
    Item:
      type: object
      properties:
        itemCd:
          type: string
          example: "PROD_001"
        itemNm:
          type: string
          example: "Mpepo Burger"
        qty:
          type: integer
          example: 2
        prc:
          type: number
          example: 50.0
        taxblAmt:
          type: number
          example: 100.0
        taxAmt:
          type: number
          example: 10.0
        totAmt:
          type: number
          example: 110.0
    SuccessResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: Invoice submitted successfully to Tax Authority.
        authorityReferenceId:
          type: string
          example: TA_REF_123456
        invoiceId:
          type: string
          example: INV_20251003_001
    FailResponse:
      type: object
      properties:
        detail:
          type: object
          properties:
            status:
              type: string
              example: failed
            message:
              type: string
              example: Invoice rejected by Tax Authority.
            errorCode:
              type: string
              example: TA_ERR_400
            invoiceId:
              type: string
              example: INV_20251003_001

